# Generated by Django 2.1.4 on 2019-02-20 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Sezin', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('blog_category', models.CharField(choices=[('A', 'All'), ('C', 'CyberSecurity'), ('I', 'ComputerScience'), ('S', 'Skate'), ('O', 'Other')], default='C', max_length=1)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
