# Generated by Django 2.1.4 on 2019-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pdf',
            field=models.FileField(null=True, upload_to='blogs'),
        ),
    ]
